steps:
  - label: ":node: Linting"
    command: npm run lint
    plugins:
      - docker-compose#v3.9.0:
          run: app
    agents:
      queue: build

  - wait

  - label: ":aws: :s3: Deploy to Dev Environment"
    command:
      - aws s3 cp --sse AES256 --recursive locales s3://i18n-dev-asiga-com
      - aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0]=='app.dev.asiga.com'].{Id: Id}" | jq -r '.[0].Id') --paths "/*"
    env:
      AWS_ASSUME_ROLE_ARN: arn:aws:iam::037538343661:role/i18n-dev-asiga-com-deployment
    plugins:
      - artifacts#v1.9.2:
          download: "build/*"
      - cultureamp/aws-assume-role
    agents:
      queue: deploy
    branches:
      - "main"
